"""Initial Migration

Revision ID: 039ce0e39d93
Revises: 1eed85d31741
Create Date: 2021-03-02 00:17:42.750258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '039ce0e39d93'
down_revision = '1eed85d31741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('posted', sa.DateTime(), nullable=True))
    op.drop_column('comments', 'postedAt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('postedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'posted')
    # ### end Alembic commands ###
